---
name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION

categories:
  - title: ğŸš€ Features
    labels:
      - type/feat
      - type/enhancement
  - title: ğŸ› Bug Fixes
    labels:
      - type/fix
  - title: ğŸ›  Refactoring
    labels:
      - type/refactor
  - title: ğŸ“š Documentation
    labels:
      - type/docs
  - title: ğŸ§ª Tests
    labels:
      - type/test
  - title: ğŸ§¹ Maintenance
    labels:
      - type/chore
      - type/maintenance
      - type/dependencies

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

# The autolabeler section has been removed as you already use a dedicated labeler action.

template: |
  ## What's Changed

  $CHANGES

  ---
  ## New Contributors
  * @{{ contributors }} made their first contribution in #{{ number }}
